## please copy over all contents of the XDC when it is merged with othe XDC files ##

## Clock constraint for input system clock which drives MMCM for the design

## The frequency of the input clock is as per GUI selected input clock period

create_clock -period 14.259 [get_ports c0_sys_clk_p]


## Below pin LOC constraints are for system clock and system reset and

## memory related pins

set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[34]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[32]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[33]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[35]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[25]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[26]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[29]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[32]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[33]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[23]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[24]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[31]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[27]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[29]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[30]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dka_p[1]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dka_n[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[30]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[20]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[21]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_cfg_n" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_lbk0_n" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_lbk1_n" ]
set_property IOSTANDARD LVCMOS12 [ get_ports "c0_qdriv_rst_n" ]
set_property DRIVE 8 [ get_ports "c0_qdriv_rst_n" ]

set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dkb_p[1]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dkb_n[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[28]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[18]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[23]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[24]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[27]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[28]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[34]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qka_p[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[25]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[26]" ]
set_property IOSTANDARD DIFF_SSTL12 [ get_ports "c0_sys_clk_p" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_ainv" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_pe_n" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_rwa_n" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[13]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[16]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[17]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[14]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[19]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[22]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[31]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[35]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qka_n[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[18]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[19]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_lda_n" ]
set_property IOSTANDARD DIFF_SSTL12 [ get_ports "c0_sys_clk_n" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[20]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_ap" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_rwb_n" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_qvldb[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[11]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[12]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[15]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qkb_p[1]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qkb_n[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_qvldb[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[14]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[16]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[22]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_qvlda[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_ldb_n" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[18]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[19]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_ck_p[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_ck_n[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qkb_p[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qkb_n[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[9]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[10]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[20]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[21]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[5]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[15]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[11]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[17]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[13]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[16]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[17]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[14]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[15]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[12]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[5]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[7]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[8]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dka_p[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dka_n[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[6]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[12]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qka_p[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_qvlda[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[8]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[10]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[13]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[2]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[4]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[6]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[4]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[2]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[7]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[9]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_qka_n[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[9]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[11]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[6]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[2]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[3]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqb[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[3]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[8]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_dqa[10]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[4]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[5]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[7]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_qdriv_a[3]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dkb_p[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_qdriv_dkb_n[0]" ]


## These signals once asserted, stays asserted for multiple clock cycles.

## False path constraint is added to improve the HOLD timing.



set_property SLEW FAST [get_ports {c0_qdriv_ck_p[*] c0_qdriv_ck_n[*] c0_qdriv_a[*] c0_qdriv_ainv c0_qdriv_ap c0_qdriv_cfg_n c0_qdriv_lbk0_n c0_qdriv_lbk1_n }]
set_property SLEW FAST [get_ports {c0_qdriv_lda_n c0_qdriv_rwa_n }]
set_property SLEW FAST [get_ports {c0_qdriv_ldb_n c0_qdriv_rwb_n }]
set_property SLEW FAST [get_ports {c0_qdriv_dka_p[*] c0_qdriv_dka_n[*] c0_qdriv_dqa[*] }]
set_property SLEW FAST [get_ports {c0_qdriv_dkb_p[*] c0_qdriv_dkb_n[*] c0_qdriv_dqb[*] }]
set_property IBUF_LOW_PWR FALSE [get_ports {c0_qdriv_qka_p[*] c0_qdriv_qka_n[*] c0_qdriv_dqa[*] }]
set_property IBUF_LOW_PWR FALSE [get_ports {c0_qdriv_qkb_p[*] c0_qdriv_qkb_n[*] c0_qdriv_dqb[*] }]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {c0_qdriv_qka_p[*] c0_qdriv_qka_n[*] c0_qdriv_dqa[*] }]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {c0_qdriv_qkb_p[*] c0_qdriv_qkb_n[*] c0_qdriv_dqb[*] }]
set_property ODT RTT_40 [get_ports {c0_qdriv_qka_p[*] c0_qdriv_qka_n[*] c0_qdriv_dqa[*] }]
set_property ODT RTT_40 [get_ports {c0_qdriv_qkb_p[*] c0_qdriv_qkb_n[*] c0_qdriv_dqb[*] }]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_qdriv_ck_p[*] c0_qdriv_ck_n[*] c0_qdriv_a[*] c0_qdriv_ainv c0_qdriv_ap c0_qdriv_cfg_n c0_qdriv_lbk0_n c0_qdriv_lbk1_n }]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_qdriv_lda_n c0_qdriv_rwa_n }]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_qdriv_ldb_n c0_qdriv_rwb_n }]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_qdriv_dka_p[*] c0_qdriv_dka_n[*] c0_qdriv_dqa[*] }]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {c0_qdriv_dkb_p[*] c0_qdriv_dkb_n[*] c0_qdriv_dqb[*] }]
set_property PRE_EMPHASIS RDRV_NONE [get_ports {c0_qdriv_ck_p[*] c0_qdriv_ck_n[*] c0_qdriv_a[*] c0_qdriv_ainv c0_qdriv_ap c0_qdriv_cfg_n c0_qdriv_lbk0_n c0_qdriv_lbk1_n }]
set_property PRE_EMPHASIS RDRV_NONE [get_ports {c0_qdriv_lda_n c0_qdriv_rwa_n }]
set_property PRE_EMPHASIS RDRV_NONE [get_ports {c0_qdriv_ldb_n c0_qdriv_rwb_n }]
set_property PRE_EMPHASIS RDRV_NONE [get_ports {c0_qdriv_dka_p[*] c0_qdriv_dka_n[*] c0_qdriv_dqa[*] }]
set_property PRE_EMPHASIS RDRV_NONE [get_ports {c0_qdriv_dkb_p[*] c0_qdriv_dkb_n[*] c0_qdriv_dqb[*] }]
set_property DATA_RATE DDR [get_ports {c0_qdriv_ck_p[*] c0_qdriv_ck_n[*] c0_qdriv_a[*] c0_qdriv_ainv c0_qdriv_ap }]
set_property DATA_RATE SDR [get_ports {c0_qdriv_pe_n c0_qdriv_cfg_n c0_qdriv_rst_n c0_qdriv_lbk0_n c0_qdriv_lbk1_n }]
set_property DATA_RATE SDR [get_ports {c0_qdriv_lda_n c0_qdriv_rwa_n }]
set_property DATA_RATE SDR [get_ports {c0_qdriv_ldb_n c0_qdriv_rwb_n }]
set_property DATA_RATE DDR [get_ports {c0_qdriv_dka_p[*] c0_qdriv_dka_n[*] c0_qdriv_qka_p[*] c0_qdriv_qka_n[*] c0_qdriv_dqa[*] }]
set_property DATA_RATE DDR [get_ports {c0_qdriv_dkb_p[*] c0_qdriv_dkb_n[*] c0_qdriv_qkb_p[*] c0_qdriv_qkb_n[*] c0_qdriv_dqb[*] }]
set_property DATA_RATE SDR [get_ports c0_qdriv_qvlda[*] ]
set_property DATA_RATE SDR [get_ports c0_qdriv_qvldb[*] ]
set_property DRIVE 8 [ get_ports c0_qdriv_rst_n ]
## These below commands are used to create Interface ports for controller.

create_interface -quiet interface_qdriv_0
set_property interface interface_qdriv_0 [get_ports [list {c0_qdriv_dqb[34]} {c0_qdriv_dqb[32]} {c0_qdriv_dqb[33]} {c0_qdriv_dqb[35]} {c0_qdriv_dqb[25]} {c0_qdriv_dqb[26]} {c0_qdriv_dqa[29]} {c0_qdriv_dqa[32]} {c0_qdriv_dqa[33]} {c0_qdriv_dqa[23]} {c0_qdriv_dqa[24]} {c0_qdriv_dqb[31]} {c0_qdriv_dqb[27]} {c0_qdriv_dqb[29]} {c0_qdriv_dqb[30]} {c0_qdriv_dka_p[1]} {c0_qdriv_dka_n[1]} {c0_qdriv_dqa[30]} {c0_qdriv_dqa[20]} {c0_qdriv_dqa[21]} c0_qdriv_cfg_n c0_qdriv_lbk0_n c0_qdriv_lbk1_n c0_qdriv_rst_n {c0_qdriv_dkb_p[1]} {c0_qdriv_dkb_n[1]} {c0_qdriv_dqb[28]} {c0_qdriv_dqb[18]} {c0_qdriv_dqb[23]} {c0_qdriv_dqb[24]} {c0_qdriv_dqa[27]} {c0_qdriv_dqa[28]} {c0_qdriv_dqa[34]} {c0_qdriv_qka_p[1]} {c0_qdriv_dqa[25]} {c0_qdriv_dqa[26]} c0_sys_clk_p c0_qdriv_ainv c0_qdriv_pe_n c0_qdriv_rwa_n {c0_qdriv_dqb[13]} {c0_qdriv_dqb[16]} {c0_qdriv_dqb[17]} {c0_qdriv_dqb[14]} {c0_qdriv_dqb[19]} {c0_qdriv_dqb[22]} {c0_qdriv_dqa[31]} {c0_qdriv_dqa[35]} {c0_qdriv_qka_n[1]} {c0_qdriv_dqa[18]} {c0_qdriv_dqa[19]} c0_qdriv_lda_n c0_sys_clk_n {c0_qdriv_a[20]} c0_qdriv_ap c0_qdriv_rwb_n {c0_qdriv_qvldb[0]} {c0_qdriv_dqb[11]} {c0_qdriv_dqb[12]} {c0_qdriv_dqb[15]} {c0_qdriv_qkb_p[1]} {c0_qdriv_qkb_n[1]} {c0_qdriv_qvldb[1]} {c0_qdriv_dqa[14]} {c0_qdriv_dqa[16]} {c0_qdriv_dqa[22]} {c0_qdriv_qvlda[1]} c0_qdriv_ldb_n {c0_qdriv_a[18]} {c0_qdriv_a[19]} {c0_qdriv_ck_p[0]} {c0_qdriv_ck_n[0]} {c0_qdriv_qkb_p[0]} {c0_qdriv_qkb_n[0]} {c0_qdriv_dqb[9]} {c0_qdriv_dqb[10]} {c0_qdriv_dqb[20]} {c0_qdriv_dqb[21]} {c0_qdriv_dqa[5]} {c0_qdriv_dqa[15]} {c0_qdriv_dqa[11]} {c0_qdriv_dqa[17]} {c0_qdriv_dqa[13]} {c0_qdriv_a[16]} {c0_qdriv_a[17]} {c0_qdriv_a[14]} {c0_qdriv_a[15]} {c0_qdriv_a[12]} {c0_qdriv_dqb[5]} {c0_qdriv_dqb[7]} {c0_qdriv_dqb[8]} {c0_qdriv_dka_p[0]} {c0_qdriv_dka_n[0]} {c0_qdriv_dqa[6]} {c0_qdriv_dqa[12]} {c0_qdriv_qka_p[0]} {c0_qdriv_qvlda[0]} {c0_qdriv_a[8]} {c0_qdriv_a[10]} {c0_qdriv_a[13]} {c0_qdriv_dqb[2]} {c0_qdriv_dqb[4]} {c0_qdriv_dqb[6]} {c0_qdriv_dqa[4]} {c0_qdriv_dqa[2]} {c0_qdriv_dqa[7]} {c0_qdriv_dqa[9]} {c0_qdriv_qka_n[0]} {c0_qdriv_a[0]} {c0_qdriv_a[9]} {c0_qdriv_a[11]} {c0_qdriv_a[6]} {c0_qdriv_a[2]} {c0_qdriv_dqb[3]} {c0_qdriv_dqb[0]} {c0_qdriv_dqb[1]} {c0_qdriv_dqa[0]} {c0_qdriv_dqa[1]} {c0_qdriv_dqa[3]} {c0_qdriv_dqa[8]} {c0_qdriv_dqa[10]} {c0_qdriv_a[1]} {c0_qdriv_a[4]} {c0_qdriv_a[5]} {c0_qdriv_a[7]} {c0_qdriv_a[3]} {c0_qdriv_dkb_p[0]} {c0_qdriv_dkb_n[0]}]]


set_multicycle_path -setup -to [get_pins */*/*/*/*.u_xiphy_control/xiphy_control/RIU_ADDR*] 2
set_multicycle_path -hold -to [get_pins */*/*/*/*.u_xiphy_control/xiphy_control/RIU_ADDR*] 1
set_multicycle_path -setup -to [get_pins */*/*/*/*.u_xiphy_control/xiphy_control/RIU_WR_DATA*] 2
set_multicycle_path -hold -to [get_pins */*/*/*/*.u_xiphy_control/xiphy_control/RIU_WR_DATA*] 1
set_multicycle_path -setup -to [get_pins */*/*/*/*.u_xiphy_control/xiphy_control/RIU_NIBBLE_SEL*] 2
set_multicycle_path -hold -to [get_pins */*/*/*/*.u_xiphy_control/xiphy_control/RIU_NIBBLE_SEL*] 1
set_false_path -from [get_pins */*/vtc_complete_reg/C]
set_multicycle_path -setup 8 -from [get_pins */cal_done_r_reg/C]
set_multicycle_path -hold 7 -from [get_pins */cal_done_r_reg/C]
set_max_delay 5.0 -datapath_only -from [get_pins */*/cal2mcs_ready_fab_clk_level_reg/C] -to [get_pins */*/u_ready_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 5.0 -datapath_only -from [get_pins */*/addr_dec_to_mb_data_riu_r_reg[*]/C] -to [get_pins */*/u_io_read_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/mcs2cal_addr_strobe_fab_clk_lvl_xored_reg/C] -to [get_pins */*/u_io_addr_strobe_lvl_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/mcs2cal_wr_data_strobe_riu_clk_lvl_reg/C] -to [get_pins */*/u_io_write_strobe_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/mcs2cal_addr_reg[*]/C] -to [get_pins */*/u_io_addr_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins */*/mcs2cal_wr_data_reg[*]/C] -to [get_pins */*/u_io_write_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_false_path -through [get_pins u_qdriv_infrastructure/sys_rst]
set_false_path -from [get_pins  */input_rst_design_reg/C] -to [get_pins */rst_div_sync_r_reg[0]/D]
set_false_path -from [get_pins  */input_rst_design_reg/C] -to [get_pins */rst_riu_sync_r_reg[0]/D]
set_false_path -from [get_pins  */input_rst_design_reg/C] -to [get_pins */rst_mb_sync_r_reg[0]/D]
set_false_path -from [get_pins  */rst_async_riu_div_reg/C] -to [get_pins */rst_div_sync_r_reg[0]/D]
set_false_path -from [get_pins  */rst_async_mb_reg/C]      -to [get_pins */rst_mb_sync_r_reg[0]/D]
set_false_path -from [get_pins  */rst_async_riu_div_reg/C] -to [get_pins */rst_riu_sync_r_reg[0]/D]
create_waiver -internal -user QDRIV -tags "1010162" -scope -type METHODOLOGY -id CLKC-55 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "*gen_mmcme*.u_mmcme_adv_inst*" -filter {NAME =~ *inst/u_qdriv_infrastructure*}]
create_waiver -internal -user QDRIV -tags "1010162" -scope -type METHODOLOGY -id CLKC-56 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "*gen_mmcme*.u_mmcme_adv_inst*" -filter {NAME =~ *inst/u_qdriv_infrastructure*}]
create_waiver -internal -user QDRIV -tags "1010162" -scope -type METHODOLOGY -id CLKC-57 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "*plle_loop[*].gen_plle*.PLLE*_BASE_INST_OTHER*" -filter {NAME =~ *inst/u_qdriv_phy_pll*}]
create_waiver -internal -user QDRIV -tags "1010162" -scope -type METHODOLOGY -id CLKC-58 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "*plle_loop[*].gen_plle*.PLLE*_BASE_INST_OTHER*" -filter {NAME =~ *inst/u_qdriv_phy_pll*}]
